# coding: utf-8

import numpy as np
import shapely


def get_contour_sections(model, gcode_z_slices):
    """
    Slices the STL at correct heights according to Gcode extracted data (Z
    heights). Then, applies the transform collected from the 3mf position
    matrix to the sections to obtain the correct position on the build plate.
    
    Args:
        model (Mesh object): The STL model object to be sliced.
        gcode_z_slices (list): List of heights where slices should be taken.
        
    Returns:
        tuple: A tuple containing:
            - list: A list of section objects after slicing and transformation.
            - np.ndarray: The corrected center base of the model.
    """

    # Generate sections and apply transformation

    model_center_base = [0, 0, 0]
    sections_2d = model.section_multiplane(plane_origin=model_center_base,
                                           plane_normal=[0, 0, 1],
                                           heights=gcode_z_slices)

    for section in sections_2d:
        section.merge_vertices()
    
    return sections_2d, model_center_base


def get_cnc_contouring_coords(sections_2d,
                              contour_tool_radius,
                              contouring_direction):
    """
    Processes each section generated by slicing the STL at specified heights
    and returns a list of each slice with buffered contours.
    
    Args:
        sections_2d (list): A list of section objects generated from the sliced
            STL.
        contour_tool_radius (float): The radius of the contour tool.
        contouring_direction:
        
    Returns:
        list: A list of dictionaries, each containing buffered exterior and
        interior contours.
    """
    original_contours_list = list()
    # Inspect the contours slices and generate a list where each element is a
    # dict of ext or interior contours
    for section in sections_2d:
        contours = {'ext': dict(), 'int': dict()}
        for j, contour in enumerate(section.discrete):
            contour_type = ['int', 'ext'][j in section.root]
            contours[contour_type][f'contour_{j}'] = contour
        original_contours_list.append(contours)
    # Apply a buffer on every contour by the value of the tool radius, negative
    # on interiors & positive on exteriors
    buffered_contours_list = list()
    for i, contours in enumerate(original_contours_list):
        buffered_contours = {'buffered_ext': dict(), 'buffered_int': dict()}
        for j, exteriors in enumerate(original_contours_list[i]['ext'].keys()):
            polygon = shapely.Polygon(
                original_contours_list[i]['ext'][exteriors])
            buffered_polygon = polygon.buffer(contour_tool_radius,
                                              resolution=12,
                                              join_style=1,
                                              mitre_limit=0.2)
                        
            if isinstance(buffered_polygon, shapely.geometry.MultiPolygon):
                for poly in buffered_polygon.geoms:
                    if contouring_direction == "conventional":
                        inverted_coords = np.flip(
                            np.array(poly.exterior.coords), axis=0)
                        buffered_contours['buffered_ext'][
                            f'buffered_{exteriors}_{poly}'] = inverted_coords
                    else:
                        buffered_contours['buffered_ext'][
                            f'buffered_{exteriors}_{poly}'] = np.array(
                            poly.exterior.coords)
                    
            else:
                if contouring_direction == "conventional":
                    inverted_coords = np.flip(np.array(
                        buffered_polygon.exterior.coords), axis=0)
                    buffered_contours['buffered_ext'][
                        f'buffered_{exteriors}'] = inverted_coords
                else:
                    buffered_contours['buffered_ext'][
                        f'buffered_{exteriors}'] = np.array(
                        buffered_polygon.exterior.coords)

        for j, interiors in enumerate(original_contours_list[i]['int'].keys()):
            polygon = shapely.Polygon(
                original_contours_list[i]['int'][interiors])
            buffered_polygon = polygon.buffer(-contour_tool_radius,
                                              resolution=12,
                                              join_style=1,
                                              mitre_limit=0.2)
            
            if contouring_direction == "climbing":
                coords_ext = np.array(buffered_polygon.exterior.coords)
                inverted_coords_ext = np.flip(coords_ext, axis=0)
                buffered_contours['buffered_ext'][
                    f'buffered_{interiors}'] = inverted_coords_ext
                
            if isinstance(buffered_polygon, shapely.geometry.MultiPolygon):
                for poly in buffered_polygon.geoms:
                    # Traiter chaque Polygon individuellement
                    buffered_contours['buffered_int'][
                        f'buffered_{interiors}_{poly}'] = np.array(
                        poly.exterior.coords)
            else:
                # Si ce n'est pas un MultiPolygon, procéder comme avant
                buffered_contours['buffered_int'][
                    f'buffered_{interiors}'] = np.array(
                    buffered_polygon.exterior.coords)
            
        buffered_contours_list.append(buffered_contours)
    return buffered_contours_list
