import re

def raise_nonmesh_travel_speed(gcode, non_mesh_travel_speed, substractive_start_layer):
    """
    Modify MESH NON MESH travel speeds in G-code to prevent oozing after a susbstractive pahse.
    It does modificate the gcode only after the specified substractive starting layer.

    Args:
        gcode (list): the gcode generated by your slicer.
        non_mesh_travel_speed (float): The desired non-mesh travel speed in the G-code.
        substractive_start_layer (int): The layer number from which hybridization begins.

    Returns:
        None

    Note:
        This function modifies the travel speeds in G-code to adjust the non-mesh travel speed to avoid
        oozing issues. It starts making modifications after detecting the specified substractive_start_layer
        in the G-code.

    Example:
        gcode = ["G1 X10 Y10 F300", "G1 X20 Y20 F300", ...]
        non_mesh_travel_speed = 150
        substractive_start_layer = 5
        raise_nonmesh_travel_speed(gcode, non_mesh_travel_speed, substractive_start_layer)
    """
    # Detect the starting line number for modifications
    for i, line in enumerate(gcode):
        if line.startswith(";LAYER:") and int(line[7:]) == substractive_start_layer:
            start_line = i - 1

    # Iterate through the G-code lines, modify travel speeds
    # and store the line numbers and previous speeds
    mesh_speed_dict = []
    for i, line in enumerate(gcode[start_line:], start=start_line):
        if line == ';LAYER CHANGE':
            target_line_number = i + 4
            target_line = gcode[target_line_number]
            splited_target_line = target_line.split()
            work_type = splited_target_line[0]
            for element in splited_target_line:
                if element.startswith('F'):
                    current_speed = element[1:]
            gcode[target_line_number] = gcode[target_line_number].replace(f'F{current_speed}', f'F{non_mesh_travel_speed}')
            dicto = {}
            dicto["speed"] = current_speed
            dicto["to_modify_line_number"] = target_line_number
            mesh_speed_dict.append(dicto)

    # Re-insert the previous speed just after the modified lines to prevent unintended issues
    for i, line in reversed(list(enumerate(mesh_speed_dict))):
        line_number_to_insert = mesh_speed_dict[i]['to_modify_line_number'] + 1
        speed = mesh_speed_dict[i]['speed']
        gcode.insert(line_number_to_insert, f"{work_type} F{speed}")

def extract_layer_data(gcode, substractive_start_layer, layer_height):
    """
    Extract data from the G-code.

    Args:
        gcode (list): The G-code generated by your slicer.
        substractive_start_layer (int): The layer number from which hybridization begins.
        layer_height (float): Layer height of additive process.

    Returns:
        - List of dictionaries containing layer information, including layer number, Z-height,
            and starting/ending line numbers in the gcode.
        - List of Z heights where CNC contouring paths will have to be generated.

    Note:
        This function extracts layer data and Z-levels from the G-code to determine where CNC contouring paths
        should be generated. It starts data extraction from the specified substractive_start_layer and uses
        the layer_height to calculate Z-levels.

    Example:
        gcode = ["G1 X10 Y10 Z0.2", "G1 X20 Y20 Z0.4", ...]
        substractive_start_layer = 5
        layer_height = 0.2
        gcode_datas, gcode_z_slices = extract_layer_data(gcode, substractive_start_layer, layer_height)
    """
    gcode_datas = []
    gcode_z_slices = []
    for index, line in enumerate(gcode):
        match = re.search('Z([0-9.]+)', line)
        if match :
            z_current_value = float(match.group(1))

        if line[0:7] == ";LAYER:" and int(line[7:]) >= (substractive_start_layer-1):
            layer_data = {
                "layer_number": int(line[7:]),
                "layer_z_height": z_current_value,
                "layer_starting_line": index
            }
            gcode_datas.append(layer_data)
            gcode_z_slices.append(round(z_current_value - layer_height, 3))
    # Sometimes, the last slice can be problematic because the module would slice in the 'nothing', since the heights are exacts.
    # We modify the last slice by 0.01mm so it always have something to slice.
    gcode_z_slices[-1]=gcode_z_slices[-1]-0.01

    for i, line in enumerate(reversed(gcode)):
        if line == ';MESH:NONMESH':
            end_line_index = len(gcode) - i - 1

        if line.startswith(";LAYER:"):
            layer_number = int(line[7:])
            for data in gcode_datas:
                if data['layer_number'] == layer_number:
                    data['layer_ending_line'] = end_line_index

    return gcode_datas,gcode_z_slices